# Generated by Django 3.2.13 on 2022-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.SlugField(unique=True)),
                ('http_url', models.URLField(max_length=255, verbose_name='Сокращаемая ссылка')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('counts_of_visits', models.IntegerField(default=0)),
            ],
        ),
    ]
